spring.application.name=restaurant-backend

# ==========================================
# MYSQL DATABASE
# ==========================================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/restaurant_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================================
# SERVER
# ==========================================

server.port=${PORT:8080}

# ==========================================
# JWT
# ==========================================

app.jwt.secret=${JWT_SECRET:SpiceRouteLocalDevelopmentSecretKey2026ChangeBeforeDeployment}
app.jwt.expiration-minutes=120

# ==========================================
# EMAIL / GMAIL SMTP
# ==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_APP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false

# ==========================================
# FRONTEND / PASSWORD RESET
# ==========================================

app.frontend.base-url=http://localhost:5173
app.password-reset.expiration-minutes=15

# ==========================================
# GOOGLE LOGIN
# ==========================================

app.google.client-id=${GOOGLE_CLIENT_ID}
spring.mail.properties.mail.smtp.ssl.enable=true
